server:
  port: 3000

app:
  dundie-delivery-chunk-size: ${DUNDIE_DELIVERY_CHUNK_SIZE:10000}
  sentinel:
    quantity-to-search: 10
    delayed-minutes: 1

spring:
  application:
    name: dundie-awards
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

springdoc:
  api-docs:
    path: /openapi