server:
  port: 3000

app:
  dundie-delivery-chunk-size: ${DUNDIE_DELIVERY_CHUNK_SIZE:10000}
  dundie-count-cache-minutes: ${COUNT_CACHE_MINUTES:5}
  sentinel:
    quantity-to-search: ${SENTINEL_QUANTITY_TO_SEARCH:10}
    delayed-minutes: ${SENTINEL_DELAYED_MINUTES:1}

spring:
  application:
    name: dundie-awards
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

springdoc:
  api-docs:
    path: /openapi